/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentChat: typeof import('./src/components/AgentChat.vue')['default']
    Map3DInterface: typeof import('./src/components/Map3DInterface.vue')['default']
    MapCanvas: typeof import('./src/components/MapCanvas.vue')['default']
    NavigationMap: typeof import('./src/components/NavigationMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanEmpty: typeof import('vant/es')['Empty']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    ZoomableMapCanvas: typeof import('./src/components/ZoomableMapCanvas.vue')['default']
  }
}
